
CREATE TABLE banks (
    key SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

INSERT INTO banks (name) VALUES
('SWEDBANK'),
('IKANOBANKEN'),
('JPMORGAN'),
('NORDEA'),
('CITIBANK'),
('HANDELSBANKEN'),
('SBAB'),
('HSBC'),
('BRYAN BANK ENTERPRISE'),
('NORDNET');
