services:
  db:
    image: postgres:13
    container_name: rust-bank-api-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rustapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rust_api:
    build:
      context: ./bank-api
      dockerfile: Dockerfile
    container_name: rust-bank-api
    depends_on:
      - db
      - kafka
    ports:
      - "8070:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/rustapi

  php-api:
    build:
      context: ./person-api
      dockerfile: Dockerfile
    ports:
      - "8060:80"
    container_name: person-api
    depends_on:
      - kafka

  account-api:
      build:
        context: ./account-project
        dockerfile: Dockerfile
      container_name: account-api
      ports:
        - "8080:8080"

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    expose:
      - "9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

volumes:
  postgres_data:
